### ISSUE TITLE
Not able to find location of mbp_weights_win03_weight05

### ISSUE THREAD

**Issue by alchemician** [bala1144/Imitator#1]
Hello author - thank you for the great work!

I am trying to run the imitator/test/test_model_external_audio.py, but I receive an error that projects/dataset/voca_face_former/mbp_weights_win03_weight05 is not present. 

Can you please guide me where to find it or how to create projects/dataset/voca_face_former in full?

I am using https://huggingface.co/facebook/wav2vec2-base-960h/tree/main for wav2vec2-base-960h folder currently. If it's not the correct, please let me know,

Thank you in advance!

**Comment by xopclabs** [comment]
A script for extracting weights for lip contact loss would be highly appreciated

**Comment by bala1144** [comment]
Added to the weights here: assets/release/mbp_weights_win03_weight05.zip. Please pull recent version of the code, unzip the weights and updates in the weights path in cfg "cfg/generalized_model/imitator_gen_ab_mbp_vel10.yaml"
