### ISSUE TITLE
Running Imitator on Mac

### ISSUE THREAD

**Issue by Darrow8** [bala1144/Imitator#11]
Hi all, 

I was able to get Imitator to work on Mac. Make sure you have installed [wget](https://stackoverflow.com/questions/33886917/how-to-install-wget-in-macos). Follow the linux commands, except change line 7 of `install.sh` to the version of python your machine is running. For me this was: 
`conda create -n $env_name python=3.11.5`

**Comment by bala1144** [comment]
added to the readme, thanks !
