### ISSUE TITLE
How to obtain the templates.pkl file

### ISSUE THREAD

**Issue by huang-1030** [bala1144/Imitator#13]
Thank you for sharing your project. I encountered a problem while running the test_model_external_audio.py file, which shows 

FileNotFoundError: [Errno 2] No such file or directory: 'imitator\\test\\projects/dataset/voca_face_former\\templates.pkl'.

How should I retrieve this pkl file

**Comment by bala1144** [comment]
You have to follow the data processing setup mentioned in the readme and get the template.pkl for the voca-set, which unfortunately we cannot provide.
