### ISSUE TITLE
Personalized stage not converging with new id

### ISSUE THREAD

**Issue by RAJA-PARIKSHAT** [bala1144/Imitator#14]
I used pretrained first-stage weights and ran training for the second stage for one of the custom ids. But the predicted output seems to have a constant offset in the jaw.
https://drive.google.com/drive/folders/1K1r6LgL3U5vIMMc2jzWaOxmhT8qqQhs6?usp=sharing
the folder contains both predicted and ground truth renders.

**Comment by wzx7084** [comment]
May I ask how the yaml file was set when you carried out the second stage of training? Why did the mouth shape of the video characters inferred after I completed the training not change？

**Comment by bala1144** [comment]
@RAJA-PARIKSHAT t looks like the model didn't converge. Based on how different the test model distribution is compared to the training distribution, you might need more data or model capacity. For debugging, you could try overfitting the entire model(not stage 1 or stage 2) to your entire custom data of the subject, as it should work in that case. If it does, then you can reduce the model/data used for fine-tuning to better understand the issue.
