### ISSUE TITLE
Training in Generalized Model Implementation

### ISSUE THREAD

**Issue by Priyabrata-M** [bala1144/Imitator#16]
In the implementation of the Generalized Model, why is the complete network being trained during the training phase? Specifically, both the style embedding module and the motion decoder are being trained.

Ideally, the style embedding module and the motion decoder should not be trained during stage 1 of the training process.

Could you please help me understand this, or am I missing something?

**Comment by bala1144** [comment]
We train our model using the VOCA dataset, which contains 8 training subjects. Specifically, we use a one-hot style vector for training the model on this dataset. We refer to this as the generalization stage, during which the motion decoder learns the motion space of the 8 training subjects.

During the personalization stage, we initialize with the style vector of one of the training subjects and personalize it to the target subject's motion. Here the motion decoder models  only person-specific motion.

An alternative approach would be to remove the style vector during generalized training. However, this method is inefficient as the model would learn an average motion of the VOCA training set, resulting in less expressiveness. Consequently, it would be more challenging to capture high-frequency motion details during the personalization stage.
