### ISSUE TITLE
About Training personalized model

### ISSUE THREAD

**Issue by wzx7084** [bala1144/Imitator#17]
I ran the personal style training code according to the steps you provided, but the mouth shape of the video character inferred by the trained model did not change, I want to know what is the problem?

**Comment by bala1144** [comment]
Did you try the style personalisation on the voca test, which the config in the repo is set to. This should work. Please use the style optimization on the voca testset to get familiar with the code before testing on your personal data.

**Comment by wzx7084** [comment]
yes , i try the style personalisation on the voca test.
My parameters are as follows:
stg01:

lightning:
trainer:
max_epochs: 20
check_val_every_n_epoch: 1
save_top_k: 1
progress_bar_refresh_rate: 50
early_stopping_metric:
patience: 10 # with parameters check_val_every_n_epoch=10 and patience=3, the trainer will perform at least 40 training
mode: min
verbose: True
strict: True # whether to crash the training if monitor is not found in the validation metrics.

model:
target: imitator.pl_style_trainer.Style_only_optim
params:
optim_params:
lr: 0.0001
weight_decay: 0
lr_sch_factor: 0.85
lr_sch_patience: 5000
monitor: val/net_loss
nn_model_cfg:
target: imitator.models.nn_model.imitator
params:
dataset: "vocaset"
vertice_dim: 15069
feature_dim: 64
period: 30
gradient_accumulation_steps: 1
num_identity_classes: 8
train_teacher_forcing: Flase # if True; we run audio feat extraction for every epoch
wav2vec_model: Imitator/wav2vec2-base-960h
wav2vec_static_features: False
# dec layers
num_dec_layers: 5
fixed_channel: True
style_concat: False
# train details
train_subjects: "FaceTalk_170731_00024_TA"
init_from_ckpt: /nfs01/projects/50500878/s120222227084/Imitator/pretrained_model/subj0024_stg02_04seq/checkpoints/epoch=000709.ckpt
loss_cfg:
full_rec_loss: 1.0
velocity_weight: 10.0

data:
target: imitator.data.data_loader_actor_wise_custom_init.DataModuleFromConfig
dataset: "voca_former_vert_pred_full_training"
params:
dataset: "vocaset"
dataset_root: "/vocaset"
wav_path: "wav"
vertices_path: "vertices_npy"
template_file: "templates.pkl"
num_iden_cls: 8
train_subjects_all: "FaceTalk_170728_03272_TA FaceTalk_170904_00128_TA FaceTalk_170725_00137_TA FaceTalk_170915_00223_TA FaceTalk_170811_03274_TA FaceTalk_170913_03279_TA FaceTalk_170904_03276_TA FaceTalk_170912_03278_TA"
default_init_subject: "FaceTalk_170725_00137_TA"
train_subjects: "FaceTalk_170731_00024_TA"
sequence_for_training: "1 5"
val_subjects: "FaceTalk_170731_00024_TA"
sequence_for_validation: "19 21"
test_subjects: "FaceTalk_170731_00024_TA"
sequence_for_testing: "21 41"

stg02:
lightning:
trainer:
max_epochs: 20
check_val_every_n_epoch: 1
save_top_k: 1
progress_bar_refresh_rate: 50
early_stopping_metric:
patience: 10 # with parameters check_val_every_n_epoch=10 and patience=3, the trainer will perform at least 40 training
mode: min
verbose: True
strict: True # whether to crash the training if monitor is not found in the validation metrics.

model:
target: imitator.pl_style_trainer.Style_and_disp_final_layer_optim_voca
params:
optim_params:
lr: 0.0001
weight_decay: 0
lr_sch_factor: 0.85
lr_sch_patience: 5000
monitor: val/net_loss
nn_model_cfg:
target: imitator.models.nn_model.imitator
params:
dataset: "vocaset"
vertice_dim: 15069
feature_dim: 64
period: 30
gradient_accumulation_steps: 1
num_identity_classes: 8
train_teacher_forcing: Flase # if True; we run audio feat extraction for every epoch
wav2vec_model: projects/dataset/voca_face_former/wav2vec2-base-960h
wav2vec_static_features: False
# dec layers
num_dec_layers: 5
fixed_channel: True
style_concat: False
# train details
train_subjects: "FaceTalk_170731_00024_TA"
init_from_ckpt: /nfs01/projects/50500878/s120222227084/Imitator/LLOG/logs/2024-07-23T10-30-36_subj0024_stg01_04seq_ADAM_nep20/checkpoints/last.ckpt
full_rec_loss: 1.0
velocity_weight: 10.0

data:
target: imitator.data.data_loader_actor_wise_custom_init.DataModuleFromConfig
dataset: "voca_former_vert_pred_full_training"
params:
dataset: "vocaset"
dataset_root: "projects/dataset/voca_face_former"
wav_path: "wav"
vertices_path: "vertices_npy"
template_file: "templates.pkl"
num_iden_cls: 8
train_subjects_all: "FaceTalk_170728_03272_TA FaceTalk_170904_00128_TA FaceTalk_170725_00137_TA FaceTalk_170915_00223_TA FaceTalk_170811_03274_TA FaceTalk_170913_03279_TA FaceTalk_170904_03276_TA FaceTalk_170912_03278_TA"
default_init_subject: "FaceTalk_170725_00137_TA"
train_subjects: "FaceTalk_170731_00024_TA"
sequence_for_training: "1 5"
val_subjects: "FaceTalk_170731_00024_TA"
sequence_for_validation: "19 21"
test_subjects: "FaceTalk_170731_00024_TA"
sequence_for_testing: "21 41"

However, in the final visualization results, the mouth does not change.

**Comment by bala1144** [comment]
I tested the same setup locally, and it works on my machine. There might be an issue with your data processing. Could you debug that? Additionally, can you try inferencing on the pretrained models to see if you can reproduce results ? It should be possible to identify the problem if it exists.
