### ISSUE TITLE
speaker identity of motion decoder

### ISSUE THREAD

**Issue by duan348733684** [bala1144/Imitator#5]
Thank you for your work. 
How is the speaker identity obtained in the motion decoder module?
The paper mentioned the use of MICA,  but I couldn't find it in the code. 
Can you provide some hints? 
Thank you.

**Comment by bala1144** [comment]
Steps for extracting speaker identity:
1. Get a reference video for the speaker
2. Run [MICA](https://github.com/Zielon/metrical-tracker) to extract the pseudo-tracked meshes for the sequence.
3. Process the meshes and extract the audio from the video.
4. Follow the personalized model training procedure to learn the speaker identity.
