### ISSUE TITLE
loss is equal to zero during training

### ISSUE THREAD

**Issue by vitrus8008** [bala1144/Imitator#7]
Epoch 1: val/net_loss reached 0.00000 (best 0.00000)

Has anyone managed to get the training to work?

**Comment by vitrus8008** [comment]
Nevermind, the loss is just smaller than 1e-5, so it's not displayed during training.
Finally, it seems to work.

**Comment by duan348733684** [comment]
> Epoch 1: val/net_loss reached 0.00000 (best 0.00000)
> 
> Has anyone managed to get the training to work?

Have you trained sucessfully?

**Comment by duan348733684** [comment]
> Nevermind, the loss is just smaller than 1e-5, so it is not displayed during training. Training seems to work.
@vitrus8008 
Have you trained sucessfully?

**Comment by vitrus8008** [comment]
Yes

**Comment by duan348733684** [comment]
> Yes

@vitrus8008 
can you share how did you train? I failed.
